name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: required libraries install
      run: sudo apt-get install pango
    - name: rustup toolchain install
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy,rustfmt
    - name: Format
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy --verbose --all-targets --workspace
    - name: Run tests
      run: cargo test --verbose --workspace
